;;; Automatically generated by ‘recentf’ on Sat Aug 15 20:01:57 2026.

(setq recentf-list
      '(
        "~/org/todo.org"
        "~/org/slack.org"
        "~/org/paper-listup.org"
        "~/org/meeting.org"
        "~/org/calendar.org"
        "~/org/agentic-memory.org"
        "~/org/daily.org"
        "~/.emacs.d/config.org"
        "/usr/share/emacs/30.2/lisp/use-package/use-package-ensure.el.gz"
        "/usr/share/emacs/30.2/lisp/use-package/use-package-delight.el.gz"
        "/usr/share/emacs/30.2/lisp/use-package/use-package-diminish.el.gz"
        "/usr/share/emacs/30.2/lisp/bind-key.el.gz"
        "/usr/share/emacs/30.2/lisp/use-package/use-package-bind-key.el.gz"
        "/usr/share/emacs/30.2/lisp/ansi-osc.el.gz"
        "/usr/share/emacs/30.2/lisp/ansi-color.el.gz"
        "/usr/share/emacs/30.2/lisp/emacs-lisp/ring.el.gz"
        "/usr/share/emacs/30.2/lisp/comint.el.gz"
        "/usr/share/emacs/30.2/lisp/progmodes/compile.el.gz"
        "/usr/share/emacs/30.2/lisp/emacs-lisp/bytecomp.el.gz"
        "/usr/share/emacs/30.2/lisp/use-package/use-package-core.el.gz"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
